### PR TITLE
fix clippy warnings

### PR DESCRIPTION
**Pull request by madmo**

### CODE REVIEW

**Comment by dylif** [comment]
@bbustin I'm not sure if this PR is still applicable but might be worth a look

**Comment by bbustin** [comment]
Thanks @dylif. Somehow I missed the PR. I’ll take a look tomorrow and see, but I suspect the PR will be good and I’ll merge it in.

**Comment by dylif** [comment]
Sounds good. Thanks for taking the time to look at this!

**Review by bbustin — APPROVED** [review]
Thanks @madmo. Sorry for the delay in getting this in. I had not seen the notification. Thanks @dylif for bringing it to my attention.

**Pull request merged**
